### ISSUE TITLE
Failed when try to rescue my Xcode 7.1

### ISSUE THREAD

**Issue by CaliosD** [ForkPanda/RescueXcodePlug-ins#1]
It failed when I try to run it.

```
....
Try to rescue your Xcode 7.1 ...
Ok
sh: line 26: [: too many arguments

Error!Cannot find any config of Plug-ins in your Library!
```

Any solution? Thanks in advance.

**Comment by ForkPanda** [comment]
Try to run it again.And restart your Xcode.
I'll fix it later.

**Comment by ForkPanda** [comment]
Just a echo error, now I have fix it.
And the function is not affected.
Wish it can help you to solve the problem.

**Comment by CaliosD** [comment]
Yep, it works when tried again. It did solve my problem. Thank you, buddy. :+1:
